#!/usr/bin/env bash

# Case statement playground

for arg in "$@"; do
	case "$arg" in
		-h|--help)
			echo "Usage:"
			echo "  ${0##*/} [-v | --verbose] -f | --file <file>"
			echo "  ${0##*/} -h | --help"
			exit 0
			;;
	esac
done


while [[ "$#" -gt 0 ]]; do
	case "$1" in
		-v|--verbose)
			echo 'Verbose mode on'
			shift
			;;
		-f|--file)
			if [[ "$2" ]]; then
				echo "File specified: $2"
			else
				echo 'No file specified'
				exit 1
			fi
			file="$2"
			shift 2
			;;
	esac
done
