#!/usr/bin/env bash

# Case statement playground
# Get ip info based on flag passed

print_usage () {
	# Print usage and exit with error.
	echo "Try $script_name --help for more information."
	exit 1
}

print_help () {
	# Print help and exit with success.
	local help
	read -r -d '' help <<-EOF
		$script_name - Simple tool to print public ip address 

		Usage:
		  $script_name -4 | -6 | -a
		  $script_name -h | --help

		Description:
		  Provides a playground for adding and editing options passed to the script.

		Options:
		  -h, --help		Show help message and exit
		  -4			Get IPv4 address
		  -6			Get IPv6 address
		  -a, --all		Get both IPv4 and IPv6 addresses
EOF
	#printf '%s\n' "$help"
	echo "$help"
	exit 0
}

get_ip () {
	local ip_check_url='icanhazip.com'
	local ip_prefix

	# Get IP address based on the flag passed
	if [[ "$ipv4" = 1 ]]; then
		ip_prefix='ipv4.'
	elif [[ "$ipv6" = 1 ]]; then
		ip_prefix='ipv6.'
	elif [[ "$all" = 1 ]]; then
		ip_prefix='ipv{4,6}.'
	fi
	curl "https://$ip_prefix$ip_check_url"
	exit 0
}

script_name="${0##*/}"

if [[ "$#" = 0 ]]; then
	echo 'Missing argument'
	print_usage
fi

for arg in "$@"; do
	case "$arg" in
		-h|--help)
			print_help
			;;
	esac
done

if [[ "$#" -gt 1 ]]; then
	echo 'Only one argument allowed'
	print_usage
fi

case "$1" in
	-4)
		ipv4=1
		echo 'IPv4 selected'
		get_ip
		;;
	-6)
		ipv6=1
		echo 'IPv6 selected'
		get_ip
		;;
	-a|--all)
		all=1
		echo 'IPv4 and IPv6 selected'
		get_ip
		;;
	*)
		echo 'Unknown argument'
		print_usage
		;;
esac
